### ISSUE TITLE
Newspaper Batch Export: empty fileGrp sections

### ISSUE THREAD

**Issue by henning-gerhardt** [goobi/goobi-production#302]
Exporting a newspaper batch resulting in empty fileGrp sections inside meta file:

```xml
<mets:fileSec>
    <mets:fileGrp USE="DOWNLOAD"/>
    <mets:fileGrp USE="ORIGINAL"/>
    <mets:fileGrp USE="MIN"/>
    <mets:fileGrp USE="DEFAULT"/>
    <mets:fileGrp USE="THUMBS"/>
    <mets:fileGrp USE="MAX"/>
</mets:fileSec>
```

Exporting same newspaper processes through normal export (goobi script, dms export button, automatic process step) contains correct fileGrp information.

**Comment by matthias-ronge** [comment]
The fix is in this line: https://github.com/goobi/goobi-production/pull/301/files#diff-7a173878b8dbc156a199d89b26ac009bR531
Simply, a `MetsMods` object must be used to read the internal format, the `MetsModsImportExport` object doesn’t read all the data. Fixing it was a prerequisite to solve #286 and happened before I inspected this issue in more detail.

**Comment by claussni** [comment]
Fixed by https://github.com/goobi/goobi-production/pull/301/files#diff-7a173878b8dbc156a199d89b26ac009bR531
